#apiVersion: v1
#kind: Service
#metadata:
#  name: k8s-web-to-nginx
#spec:
#  selector:
#    app: k8s-web-to-nginx
#  ports:
#    - port: 3333
#      targetPort: 3000
#  type: LoadBalancer
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: k8s-web-to-nginx
#spec:
#  replicas: 3
#  selector:
#    matchLabels:
#      app: k8s-web-to-nginx
#  template:
#    metadata:
#      labels:
#        app: k8s-web-to-nginx
#    spec:
#      containers:
#        - name: k8s-web-to-nginx
#          image: suketshah/k8s-web-hello:3.0.0
#          resources:
#            requests:
#              cpu: 100m
#              memory: 128Mi
#            limits:
#              cpu: 200m
#              memory: 256Mi
#          ports:
#            - containerPort: 3000
apiVersion: v1
kind: Service
metadata:
  name: k8s-web-to-nginx
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-to-nginx
  ports:
    - port: 3333
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-to-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-web-to-nginx
  template:
    metadata:
      labels:
        app: k8s-web-to-nginx
    spec:
      containers:
        - name: k8s-web-to-nginx
          image: suketshah/k8s-web-hello:3.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000